query playlists($cursor: String, $first: Int!) {
  playlists(cursor: $cursor, first: $first) {
    edges {
      node {
        description
        name
        images {
          url
        }
        owner {
          displayName
          spotifyId
        }
        tracks {
          total
        }
        spotifyId
      }
    }
    hasNextPage
    totalCount
  }
}
